# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xilinx_2020/MY_Basys-3-Master.xdc

# Block Designs: bd/upcounter_design/upcounter_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==upcounter_design || ORIG_REF_NAME==upcounter_design} -quiet] -quiet

# IP: bd/upcounter_design/ip/upcounter_design_FND_counter_0_0/upcounter_design_FND_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==upcounter_design_FND_counter_0_0 || ORIG_REF_NAME==upcounter_design_FND_counter_0_0} -quiet] -quiet

# XDC: bd/upcounter_design/upcounter_design_ooc.xdc
